name: Deploy AES website to test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v6
        with:
          lfs: true

      - name: Deploy website via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
         protocol: ftps
         security: loose
          port: 21
          server-dir: AES_ukr_clean_2_3/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
